### ISSUE TITLE
最近几天打开修改定位,地图是空白,请问如何修改

### ISSUE THREAD

**Issue by ejkiup159** [GDaily/location-cleaned#1]
最近几天打开修改定位,地图是空白,请问如何修改
###

**Comment by docvirt** [comment]
> 
> 
> 最近几天打开修改定位,地图是空白,请问如何修改
edit libadd.dll

**Comment by ejkiup159** [comment]
thanks~~ I've started using ifakelocation.

GDaily ***@***.***> 于2022年12月7日周三 12:08写道：
